version = 1

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "csirtg-mail/Dockerfile",
    "docker-travis-ci-cli/Dockerfile",
    "eslint/Dockerfile",
    "gocritic/Dockerfile",
    "usbrip/Dockerfile",
  ]
